services:
  faker:
    build: ./faker-server
    container_name: faker
    ports:
      - "3000:3000"
    
  crow-server:
    build:
      context: .
      dockerfile: crow-server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    container_name: crow-server
    
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      - REDIS_MAXMEMORY=1mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    restart: unless-stopped
    container_name: redis

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  yandex-tank:
    build: ./loadtest
    container_name: yandex-tank
    ports:
      - "3001:3001"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  node-exporter-crow:
    image: prom/node-exporter:latest
    container_name: node-exporter-crow
    ports:
      - "9101:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    restart: unless-stopped

  node-exporter-faker:
    image: prom/node-exporter:latest
    container_name: node-exporter-faker
    ports:
      - "9102:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    restart: unless-stopped

  node-exporter-redis:
    image: prom/node-exporter:latest
    container_name: node-exporter-redis
    ports:
      - "9103:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    restart: unless-stopped

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana-dashboards-provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana-datasources-provisioning.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    restart: unless-stopped


volumes:
  portainer_data:
  grafana_data:
